"""Alembic migration script template"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0bfeb2bbddcd'
down_revision: Union[str, None] = '2e819df3a844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('license_type', sa.String(), nullable=True))
    op.add_column('licenses', sa.Column('issuing_authority', sa.String(), nullable=True))
    op.add_column('licenses', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'is_active')
    op.drop_column('licenses', 'issuing_authority')
    op.drop_column('licenses', 'license_type')
    # ### end Alembic commands ###
