"""Alembic migration script template"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '658827d722ac'
down_revision: Union[str, None] = '714943369093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ce_courses', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ce_courses', 'is_active')
    # ### end Alembic commands ###
