"""Alembic migration script template"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '714943369093'
down_revision: Union[str, None] = '0bfeb2bbddcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
